
version: 2

models:

  - name: milestone1_1
    description: "A model to calculate monthly average NAV and prices for each scheme"
    columns:
      - name: nav_month
        tests:
          - not_null
      - name: code
        tests:
          - not_null
      - name: nav_avg
        tests:
          - not_null
      - name: repurchase_avg
        tests:
          - not_null
      - name: sale_avg
        tests:
          - not_null


  - name: milestone1_2
    description: "A model to find out each schemes Max and Min NAV value and Date it occurred"
    columns:
      - name: nav_date
        tests:
          - not_null
      - name: code
        tests:
          - not_null
      - name: maximum_nav
        tests:
          - not_null
      - name: minimum_nav
        tests:
          - not_null

  - name: milestone2_1ytd
    description: "A model to find Mutual fund performance - including YTD returns"
    columns:
      - name: ytd
        tests:
          - not_null
      - name: code
        tests:
          - not_null

  - name: milestone2_1mtd
    description: "A model to find Mutual fund performance - including MTD returns"
    columns:
      - name: mtd
        tests:
          - not_null
      - name: code
        tests:
          - not_null

  - name: milestone2_1oneyear
    description: "A model to find Mutual fund performance - including One Year returns"
    columns:
      - name: oneyear_returns
        tests:
          - not_null
      - name: code
        tests:
          - not_null

  - name: milestone2_4ytd
    description: "A model to find ytd results for all funds in liquid fund category"
    columns:
      - name: ytd
        tests:
          - not_null
      - name: code
        tests:
          - not_null
      - name: category_id
        tests:
          - not_null